environment:
  name: "Breakout-v4"
  render_mode: "rgb_array"
  max_steps: 10000

model:
  input_shape: [4, 84, 84]  # [channels, height, width]
  num_actions: 3
  filename: "model_weights.pth"

training:
  num_episodes: 100000
  max_steps: 10000
  batch_size: 32
  learning_rate: 0.0001
  gamma: 0.99
  eps: 1.0  # Starting epsilon
  replay_buffer_size: 40000
  warmup_steps: 100000

logging:
  base_log_dir: "runs"
  checkpoint_freq: 10
  eval_freq: 100
  histogram_freq: 50
  logs_path: "logs/training_stats.json"

run_management:
  max_session_duration: 28800  # 8 hours in seconds
  save_frequency_seconds: 1200  # Save every 30 minutes
  resume_from: almost_rainbow  # Set to run ID to resume (e.g. "dqn_20240220-123456")
